import { Metadata } from "next";
import "./globals.css";

import {cn} from "@/lib/utils"
import { Providers } from "@/providers";


export const metadata: Metadata = {
  title: "Lojinha NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={cn("bg-gray-600 text-white min-h-screen antialiased")}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
